# Generated by Django 4.0 on 2022-09-02 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_product_last_month_12mis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='产品id')),
            ],
            options={
                'db_table': 'Product_id',
            },
        ),
        migrations.AddField(
            model_name='product_last_month_12mis',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chart.product_id'),
        ),
    ]
