# Generated by Django 4.0 on 2022-09-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_product_id_product_last_month_12mis_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_id',
            name='product_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='产品名称'),
        ),
    ]
