# Generated by Django 4.0 on 2022-09-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_service_station_information'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service_station_information',
            table='Service_station_information',
        ),
    ]
