# Generated by Django 4.0 on 2022-09-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_alter_service_station_information_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='area_claim_frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=128, verbose_name='大区地址')),
                ('frequency', models.IntegerField(verbose_name='索赔频次')),
                ('ownership', models.IntegerField(verbose_name='地区拥有量')),
                ('failurae_rate', models.CharField(max_length=32, verbose_name='索赔率')),
                ('Date_of_claim', models.DateTimeField(verbose_name='索赔年月')),
                ('car_type', models.CharField(max_length=32, verbose_name='车型')),
                ('platform', models.CharField(max_length=64, verbose_name='平台')),
                ('let', models.CharField(max_length=32, verbose_name='排放')),
                ('purpose', models.CharField(max_length=32, verbose_name='用途')),
            ],
            options={
                'db_table': 'area_claim_frequency',
            },
        ),
        migrations.CreateModel(
            name='E6_platform_mis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_mis', models.CharField(max_length=128, verbose_name='日期')),
                ('mis_12', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis_9', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='9mis的值')),
                ('mis_6', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='6mis的值')),
                ('mis_3', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='3mis的值')),
            ],
            options={
                'db_table': 'E6_platform_mis',
            },
        ),
        migrations.CreateModel(
            name='Frequency_of_claims_by_car_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_claim', models.CharField(max_length=32, verbose_name='索赔日期')),
                ('frequency', models.IntegerField(verbose_name='索赔频次')),
                ('car_type', models.CharField(max_length=32, verbose_name='车型')),
                ('platform', models.CharField(max_length=64, verbose_name='平台')),
                ('let', models.CharField(max_length=32, verbose_name='排放')),
                ('purpose', models.CharField(max_length=32, verbose_name='用途')),
            ],
            options={
                'db_table': 'Frequency_of_claims_by_car_type',
            },
        ),
        migrations.CreateModel(
            name='J6_Highway_Production_Month_12MIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_samples', models.IntegerField(verbose_name='索赔数量')),
                ('date', models.DateTimeField(verbose_name='索赔日期')),
                ('mis0', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis1', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis2', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis3', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis4', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis5', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis6', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis7', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis8', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis9', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis10', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis11', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('mis12', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('Statistics_month', models.DateTimeField(verbose_name='统计日期')),
            ],
            options={
                'db_table': 'J6_Highway_Production_Month_12MIS',
            },
        ),
        migrations.CreateModel(
            name='let_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('let', models.CharField(max_length=128, verbose_name='排放')),
            ],
            options={
                'db_table': 'let_information',
            },
        ),
        migrations.CreateModel(
            name='mis12_platform_6DM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=64, verbose_name='平台')),
                ('mis_12', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='12mis的值')),
                ('date', models.CharField(max_length=128, verbose_name='日期')),
            ],
            options={
                'db_table': 'mis12_platform_6DM',
            },
        ),
        migrations.CreateModel(
            name='part_claim_mis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=128, verbose_name='零部件名称')),
                ('date', models.CharField(max_length=128, verbose_name='日期')),
                ('base_value', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='基础值')),
                ('current_value', models.DecimalField(decimal_places=1, max_digits=24, verbose_name='当前值')),
                ('chain_ration', models.CharField(max_length=32, verbose_name='环比')),
                ('year_on_year', models.CharField(max_length=32, verbose_name='同比')),
            ],
            options={
                'db_table': 'part_claim_mis',
            },
        ),
        migrations.CreateModel(
            name='platform_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=128, verbose_name='平台')),
            ],
            options={
                'db_table': 'platform_information',
            },
        ),
    ]
