# Generated by Django 4.0 on 2022-09-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_rename_chain_ration_part_claim_mis_chain_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area_claim_frequency',
            old_name='failurae_rate',
            new_name='failure_rate',
        ),
    ]
