# Generated by Django 4.0 on 2022-09-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0010_e6_platform_mis_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis0',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='0mis的值'),
        ),
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='1mis的值'),
        ),
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis10',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='10mis的值'),
        ),
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis11',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='11mis的值'),
        ),
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis12',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='12mis的值'),
        ),
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='2mis的值'),
        ),
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='3mis的值'),
        ),
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis4',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='4mis的值'),
        ),
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis5',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='5mis的值'),
        ),
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis6',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='6mis的值'),
        ),
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis7',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='7mis的值'),
        ),
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis8',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='8mis的值'),
        ),
        migrations.AlterField(
            model_name='j6_highway_production_month_12mis',
            name='mis9',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=24, null=True, verbose_name='9mis的值'),
        ),
    ]
