# Generated by Django 4.0 on 2022-09-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0011_alter_j6_highway_production_month_12mis_mis0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='j6_highway_production_month_12mis',
            name='date_s',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='生产月'),
        ),
    ]
